ASSET_DB = {
    "Gold":            {"symbol": "GC=F",    "market": "rohstoff"},
    "Silber":          {"symbol": "SI=F",    "market": "rohstoff"},
    "Platin":          {"symbol": "PL=F",    "market": "rohstoff"},
    "Palladium":       {"symbol": "PA=F",    "market": "rohstoff"},
    "Kupfer":          {"symbol": "HG=F",    "market": "rohstoff"},
    "Öl (WTI)":        {"symbol": "CL=F",    "market": "rohstoff"},
    "Erdgas":          {"symbol": "NG=F",    "market": "rohstoff"},
    "Nasdaq 100":      {"symbol": "QQQ",   "market": "technologie"},
    "Tech-Sektor":     {"symbol": "XLK",   "market": "technologie"},
    "iShares PHLX Semiconductor Sector Index ETF": {"symbol": "SOXX",  "market": "technologie"},
    "ARK Innovation":  {"symbol": "ARKK",  "market": "technologie"},
    "Robotik":         {"symbol": "ROBO",  "market": "technologie"},
    "Cyber Security":  {"symbol": "HACK",  "market": "technologie"},
    "Nvidia":          {"symbol": "NVDA",   "market": "technologie"},
    "AMD":             {"symbol": "AMD",    "market": "technologie"},
    "Microsoft":       {"symbol": "MSFT",   "market": "technologie"},
    "Alphabet":        {"symbol": "GOOGL",  "market": "technologie"},
    "Meta":            {"symbol": "META",   "market": "technologie"},
    "Walmart":         {"symbol": "WMT",    "market": "technologie"},
    "Amazon":          {"symbol": "AMZN",   "market": "technologie"},
    "Apple":           {"symbol": "AAPL",   "market": "technologie"},
    "Tesla":           {"symbol": "TSLA",   "market": "technologie"},
    "Eli Lilly":       {"symbol": "LLY",    "market": "pharma"},
    "American Tower":  {"symbol": "AMT",    "market": "technologie"},
    "Nio":             {"symbol": "NIO",    "market": "technologie"},
    "Alibaba":         {"symbol": "BABA",   "market": "technologie"},
    "JD.com":          {"symbol": "JD",     "market": "technologie"},
    "Energy Select Sector SPDR": {"symbol": "XLE",    "market": "rohstoff"},
    "Exxon Mobil":     {"symbol": "XOM",    "market": "rohstoff"},
    "Chevron":         {"symbol": "CVX",    "market": "rohstoff"},
    "Lithium ETF":     {"symbol": "LIT",    "market": "rohstoff"},
    "Consumer Staples": {"symbol": "XLP",    "market": "etf"},
    "Finance-Sektor":  {"symbol": "XLF",   "market": "forex"},
    "JPMorgan":        {"symbol": "JPM",    "market": "forex"},
    "Goldman Sachs":   {"symbol": "GS",     "market": "forex"},
    "Healthcare ETF":  {"symbol": "XLV",   "market": "technologie"},
    "China ETF":       {"symbol": "FXI",    "market": "technologie"},
    "MSCI China":      {"symbol": "MCHI",   "market": "technologie"},
    "Solar ETF":       {"symbol": "TAN",    "market": "technologie"},
    "Realty Income":   {"symbol": "O",       "market": "etf"},
    "RealEstate ETF":  {"symbol": "XLRE",   "market": "etf"},
    "Bitcoin":         {"symbol": "BTC",    "market": "crypto"},
    "Ethereum":        {"symbol": "ETH",    "market": "crypto"},
    "Solana":          {"symbol": "SOL",    "market": "crypto"},
    "XRP":             {"symbol": "XRP",    "market": "crypto"},
    "BNB":             {"symbol": "BNB",    "market": "crypto"},
    "Cardano":         {"symbol": "ADA",    "market": "crypto"},
    "Dogecoin":        {"symbol": "DOGE",   "market": "crypto"},
    "Avalanche":       {"symbol": "AVAX",   "market": "crypto"},
    "Polkadot":        {"symbol": "DOT",    "market": "crypto"},
    "Chainlink":       {"symbol": "LINK",   "market": "crypto"},
    "Litecoin":        {"symbol": "LTC",    "market": "crypto"},
    "TRON":            {"symbol": "TRX",    "market": "crypto"},
    "Algorand":        {"symbol": "ALGO",   "market": "crypto"},
    "DeXe":            {"symbol": "DEXE",   "market": "crypto"},
    "Euro/Dollar":     {"symbol": "EURUSD=X", "market": "forex"},
    "Dollar/Yen":      {"symbol": "JPY=X",    "market": "forex"},
    "Pfund/Dollar":    {"symbol": "GBPUSD=X", "market": "forex"},

    "Johnson & Johnson":  {"symbol": "JNJ",    "market": "pharma"},
    "Procter & Gamble":   {"symbol": "PG",     "market": "konsum"},
    "United Health":      {"symbol": "UNH",    "market": "pharma"},
    "US-Dollar Index":    {"symbol": "DX-Y.NYB", "market": "forex"},
    "GE Aerospace":       {"symbol": "GE",     "market": "technologie"},
    # ── Top 100 Krypto nach Market Cap (Coingecko, 2026-05-30) ───────────────────
    # Stablecoins/USD-Tokens und nicht-handelbare Assets gefiltert.
    "Hyperliquid":     {"symbol": "HYPE",   "market": "crypto"},
    "LEO Token":       {"symbol": "LEO",    "market": "crypto"},
    "Zcash":           {"symbol": "ZEC",    "market": "crypto"},
    "Stellar":         {"symbol": "XLM",    "market": "crypto"},
    "Monero":          {"symbol": "XMR",    "market": "crypto"},
    "WhiteBIT Coin":   {"symbol": "WBT",    "market": "crypto"},
    "Bitcoin Cash":    {"symbol": "BCH",    "market": "crypto"},
    "Toncoin":         {"symbol": "TON",    "market": "crypto"},
    "Hedera":          {"symbol": "HBAR",   "market": "crypto"},
    "Humanity":        {"symbol": "H",       "market": "crypto"},
    "MemeCore":        {"symbol": "M",      "market": "crypto"},
    "Sui":             {"symbol": "SUI",    "market": "crypto"},
    "Shiba Inu":       {"symbol": "SHIB",   "market": "crypto"},
    "Cronos":          {"symbol": "CRO",    "market": "crypto"},
    "NEAR Protocol":   {"symbol": "NEAR",   "market": "crypto"},
    "Tether Gold":     {"symbol": "XAUT",   "market": "crypto"},
    "Bittensor":       {"symbol": "TAO",    "market": "crypto"},
    "Mantle":          {"symbol": "MNT",    "market": "crypto"},
    "PAX Gold":        {"symbol": "PAXG",   "market": "crypto"},
    "Uniswap":         {"symbol": "UNI",    "market": "crypto"},
    "OKB":             {"symbol": "OKB",    "market": "crypto"},
    "Ondo":            {"symbol": "ONDO",   "market": "crypto"},
    "HTX DAO":         {"symbol": "HTX",    "market": "crypto"},
    "Pi Network":      {"symbol": "PI",     "market": "crypto"},
    "Bitget Token":    {"symbol": "BGB",    "market": "crypto"},
    "Sky":             {"symbol": "SKY",    "market": "crypto"},
    "Internet Computer": {"symbol": "ICP",  "market": "crypto"},
    "Pepe":            {"symbol": "PEPE",   "market": "crypto"},
    "Morpho":          {"symbol": "MORPHO", "market": "crypto"},
    "Ethereum Classic": {"symbol": "ETC",   "market": "crypto"},
    "Aave":            {"symbol": "AAVE",   "market": "crypto"},
    "Worldcoin":       {"symbol": "WLD",    "market": "crypto"},
    "Render":          {"symbol": "RENDER", "market": "crypto"},
    "KuCoin":          {"symbol": "KCS",    "market": "crypto"},
    "Quant":           {"symbol": "QNT",    "market": "crypto"},
    "Cosmos Hub":      {"symbol": "ATOM",   "market": "crypto"},
    "POL (ex-MATIC)":  {"symbol": "POL",    "market": "crypto"},
    "NEXO":            {"symbol": "NEXO",   "market": "crypto"},
    "Kaspa":           {"symbol": "KAS",    "market": "crypto"},
    "JUST":            {"symbol": "JST",    "market": "crypto"},
    "Ethena":          {"symbol": "ENA",    "market": "crypto"},
    "Venice Token":    {"symbol": "VVV",    "market": "crypto"},
    "Aptos":           {"symbol": "APT",    "market": "crypto"},
    "Filecoin":        {"symbol": "FIL",    "market": "crypto"},
    "Gate":            {"symbol": "GT",     "market": "crypto"},
    "XDC Network":     {"symbol": "XDC",    "market": "crypto"},
    "Flare":           {"symbol": "FLR",    "market": "crypto"},
    "Injective":       {"symbol": "INJ",    "market": "crypto"},
    "Arbitrum":        {"symbol": "ARB",    "market": "crypto"},
    "Pump.fun":        {"symbol": "PUMP",   "market": "crypto"},
    "Beldex":          {"symbol": "BDX",    "market": "crypto"},
    "FET AI":          {"symbol": "FET",    "market": "crypto"},
    "Jupiter":         {"symbol": "JUP",    "market": "crypto"},
    "Provenance":      {"symbol": "HASH",   "market": "crypto"},
    "LAB (Alpha Scan)": {"symbol": "LAB",    "market": "crypto"},
    "Stacks":          {"symbol": "STX",    "market": "crypto"},
    "Immutable X":     {"symbol": "IMX",    "market": "crypto"},
    "Optimism":        {"symbol": "OP",     "market": "crypto"},
    "The Graph":       {"symbol": "GRT",    "market": "crypto"},
    "Flow":            {"symbol": "FLOW",   "market": "crypto"},
}


def search_assets(query: str) -> list[dict]:
    q = query.lower().strip()
    results = []
    for name, data in ASSET_DB.items():
        sym_clean = data["symbol"].lower().replace("-", "").replace("=", "")
        if q in name.lower() or q in sym_clean:
            results.append({
                "name": name,
                "symbol": data["symbol"],
                "market": data["market"],
            })
    return results[:10]
