"""add_trader_judgments

Revision ID: 07e33624c537
Revises: 001
Create Date: 2026-05-31 00:26:38.481744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07e33624c537'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trader_judgments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('trader', sa.String(), nullable=False),
    sa.Column('judgment', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trader_judgments')
    # ### end Alembic commands ###